4/feature/dto
Online-Investment-Platform/stock-back-end pull request #5
Opened 2024-09-10 11:56 UTC by SEUNGBOONG

1. service controller 작성했습니다. 
2. DTO 작성 
3. 서비스 로직에서 3개만 추출해서 데이터를 보낼수있도록 가공했습니다.

2024-09-11 10:32 UTC, SEUNGBOONG commented
DTO에 주석처리해서 전달할 네임 써놨습니다.

2024-09-12 05:04 UTC, sosow0212 requested changes
수고하셨습니다. 작업하신 부분에 대해 몇 부분 리뷰 남겨봤습니다 확인해보시고 수정하시면 좋을 것 같아요~

2024-09-12 05:04 UTC, sosow0212 commented on investement/src/main/java/com/example/investment/financialRatio/service/FinancialRatioService.java
> +    private static List<FinancialRatioDTO> toFinancialRatioDTO(final JSONArray outputArray) {
static인 이유가 있을까요?
불필요하게 로직이 외부로 노출되는 것 같아요 Fetcher에서 dto 자체로 주면 안될까요?

2024-09-12 05:04 UTC, sosow0212 commented on investement/src/main/java/com/example/investment/financialRatio/service/client/FinancialRatioDataFetcher.java
> +        return new JSONObject(response.getBody());
JSONObject가 아닌 RestTemplate.exchange(o1, o2, o3.class) 를 통해서 객체로 역직렬화 할 수 있습니다

2024-09-12 05:04 UTC, sosow0212 commented on investement/src/main/java/com/example/investment/index/service/IndexService.java
> +public class IndexService {
여기도 트랜잭션이 없네요 데이터 정합성이 보장이 안 될 것 같아요 ㅠㅠ

2024-09-12 05:04 UTC, sosow0212 commented on investement/src/main/java/com/example/investment/news/service/NewsService.java
> +public class NewsService {
전체적으로 서비스의 역할이 희미해진 것 같아요 ObjectMapper도 현재 클래스에서 사용할 필요가 없어보여요 Fetcher로 이동해서 Fetcher의 역할을 더 명확하게 해주면 어떨까요?

2024-09-12 05:04 UTC, sosow0212 commented on investement/src/main/java/com/example/investment/news/service/client/NewsApiService.java
> +    }
이것도 서비스의 역할이 아닌 RestTemplateClient의 역할인 것 같습니다 혹은 requester 클래스를 따로 만들어도 될 것 같고요!

2024-09-12 05:04 UTC, sosow0212 commented on investement/build.gradle
> +    implementation 'com.fasterxml.jackson.core:jackson-annotations'
전체적으로 봤을 때 jackson이 없어도 객체로 역직렬화 할 수 있는데 한 번 RestTemplate에 어떤 메서드가 있는지 찾아보면 좋을 것 같습니다!

2024-09-12 05:10 UTC, SEUNGBOONG commented on investement/build.gradle
> +    implementation 'com.fasterxml.jackson.core:jackson-annotations'
넵 !! RestTemplate에 메서드 를 찾아서 공부해보겠습니다.

2024-09-12 05:18 UTC, SEUNGBOONG commented on investement/src/main/java/com/example/investment/common/RestTemplateClient.java
> +public class RestTemplateClient {
감사합니다 수정해보겠습니다!!

2024-09-12 05:21 UTC, SEUNGBOONG commented on investement/src/main/java/com/example/investment/financialRatio/service/FinancialRatioService.java
> +public class FinancialRatioService {
롤백 떄문에 사용하는것일까요? 
API자체를 저장해서 사용하는것이 아니라서 고민 했었습니다!! 감사합니다!

2024-09-12 05:38 UTC, SEUNGBOONG commented on investement/src/main/java/com/example/investment/financialRatio/service/FinancialRatioService.java
> +    private static List<FinancialRatioDTO> toFinancialRatioDTO(final JSONArray outputArray) {
넵 따로 Mapper를 사용해서 빼서 사용해보겠습니다!!

2024-09-12 05:42 UTC, SEUNGBOONG commented on investement/src/main/java/com/example/investment/financialRatio/service/client/FinancialRatioDataFetcher.java
> +        return new JSONObject(response.getBody());
넵 진행해보겠습니다.

2024-09-12 05:45 UTC, SEUNGBOONG commented on investement/src/main/java/com/example/investment/news/service/client/NewsApiService.java
> +    }
넵 수정해보겠습니다.

2024-09-12 07:10 UTC, merged